# Website Info
site_name: Confidential Computing Explained
site_url: https://www.mithrilsecurity.io/
site_author: Mithril Security
site_description: >-
  Tutorials to become a confidential computing expert. 

# Repository
#repo_name: mithril-security/Confidential_Computing_Explained
#repo_url: https://github.com/mithril-security/Confidential_Computing_Explained

# Configuration
theme:
  name: material
  custom_dir: docs/material_theme_customization
  features:
    - navigation.instant
    - search.highlight
    - content.tabs.link
    - navigation.sections
    - toc.integrate
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
    - scheme: default
      toggle:
        icon: material/weather-night
  icon:
    admonition:
      note: material/pencil-circle
      abstract: material/list-box-outline
      info: material/information-outline
      tip: material/fire
      success: material/check
      question: material/help-circle
      warning: material/alert
      failure: material/window-close
      danger: material/lightning-bolt-circle
      bug: material/shield-bug
      example: material/test-tube
      quote: material/format-quote-close

#Plugins
plugins:
  - search

# Customization
extra:
  homepage: https://mithrilsecurity.io
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/TxEHagpWd4
    - icon: fontawesome/brands/github
      link: https://github.com/mithril-security/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/mithril-security-company/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mithrilsecurity

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - "https://code.jquery.com/jquery-3.3.1.min.js"

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg

# Documentation tree
nav:
  - 👋 Welcome:
    - Overview: "index.md"
    - The security challenges: "docs/introduction/security-privacy-challenges.md"
    - What is Confidential Computing?: "docs/introduction/confidential-hardware-garantees.md"
  
  - 🛠️ Build your KMS:
    - Introduction: "docs/build-your-kms/intro-to-kms.md"
    - Installation: "docs/build-your-kms/installation.md"
    - Trusted VS Untrusted: "docs/build-your-kms/trusted-vs-untrusted.md"
    - Implementing calls: "docs/build-your-kms/trusted-vs-untrusted-impl.md"
    - Running the KMS in the enclave: "docs/build-your-kms/part_1_running_kms_enclave.md"
    - Building the remote attestation: "docs/build-your-kms/part_2_remote_attestation.md"